CXX = g++
CXXFLAGS = -Wall -g

proj3:  Strand.o Sequencer.o Strand.h proj3.cpp
        $(CXX) $(CXXFLAGS) Strand.o Sequencer.o Strand.h proj3.cpp -o proj3

Sequencer.o: Strand.o Sequencer.h Sequencer.cpp
        $(CXX) $(CXXFLAGS) -c Sequencer.cpp

Strand.o: Strand.h Strand.cpp
        $(CXX) $(CXXFLAGS) -c Strand.cpp

clean:
        rm *.o*
        rm *~

run:
        .\proj3